### ISSUE TITLE
DB connector

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldConnId#27]
_From [mdisabat...@gmail.com](https://code.google.com/u/101550733072735377085/) on January 16, 2012 16:01:07_

What steps will reproduce the problem? 1. Create an user with db resource
2. Update User

What is the expected output
successful operation

What do you see instead?
Exception

15:56:54.358 ERROR org.syncope.core.propagation.PropagationManager - Exception during provision on resource resource-testdb
java.lang.IllegalArgumentException: Invalid attributes set.
	at org.identityconnectors.databasetable.DatabaseTableConnector.update(DatabaseTableConnector.java:463) ~[na:na]
	at org.identityconnectors.framework.impl.api.local.operations.UpdateImpl.update(UpdateImpl.java:93) ~[framework-internal-1.3.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_29]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_29]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_29]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_29]
	at org.identityconnectors.framework.impl.api.local.operations.ConnectorAPIOperationRunnerProxy.invoke(ConnectorAPIOperationRunnerProxy.java:93) ~[framework-internal-1.3.1.jar:na]
	at $Proxy168.update(Unknown Source) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_29]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_29]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_29]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_29]
	at org.identityconnectors.framework.impl.api.local.operations.ThreadClassLoaderManagerProxy.invoke(ThreadClassLoaderManagerProxy.java:107) ~[framework-internal-1.3.1.jar:na]
	at $Proxy168.update(Unknown Source) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_29]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_29]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_29]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_29]
	at org.identityconnectors.framework.impl.api.DelegatingTimeoutProxy.invoke(DelegatingTimeoutProxy.java:107) ~[framework-internal-1.3.1.jar:na]
	at $Proxy168.update(Unknown Source) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_29]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_29]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_29]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_29]
	at org.identityconnectors.framework.impl.api.LoggingProxy.invoke(LoggingProxy.java:76) ~[framework-internal-1.3.1.jar:na]
	at $Proxy168.update(Unknown Source) ~[na:na]
	at org.identityconnectors.framework.impl.api.AbstractConnectorFacade.update(AbstractConnectorFacade.java:154) ~[framework-internal-1.3.1.jar:na]
	at org.syncope.core.propagation.ConnectorFacadeProxy.update(ConnectorFacadeProxy.java:335) ~[ConnectorFacadeProxy.class:na]
	at org.syncope.core.propagation.PropagationManager.execute(PropagationManager.java:828) [PropagationManager.class:na]
	at org.syncope.core.propagation.PropagationManager.execute(PropagationManager.java:683) [PropagationManager.class:na]
	at org.syncope.core.propagation.PropagationManager$$FastClassByCGLIB$$efc52aa3.invoke(<generated>) [cglib-2.2.jar:na]
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191) [cglib-2.2.jar:na]
	at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688) [spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110) [spring-tx-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621) [spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.syncope.core.propagation.PropagationManager$$EnhancerByCGLIB$$4559ce91.execute(<generated>) [cglib-2.2.jar:na]
	at org.syncope.core.rest.controller.UserController.update(UserController.java:322) [UserController.class:na]
	at org.syncope.core.rest.controller.UserController$$FastClassByCGLIB$$185da3bf.invoke(<generated>) [cglib-2.2.jar:na]
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191) [cglib-2.2.jar:na]
	at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688) [spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:67) [spring-security-core-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621) [spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.syncope.core.rest.controller.UserController$$EnhancerByCGLIB$$2b1678.update(<generated>) [cglib-2.2.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_29]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_29]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_29]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_29]
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176) [spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:436) [spring-webmvc-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:424) [spring-webmvc-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:790) [spring-webmvc-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719) [spring-webmvc-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:669) [...

_Original issue: http://code.google.com/p/connid/issues/detail?id=27_

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on January 16, 2012 07:02:44_

**Owner:** fabio.ma...@gmail.com  
  **Labels:** Bundle-DatabaseTable

**Comment by ilgrosso** [comment]
_From [fabio.ma...@gmail.com](https://code.google.com/u/109095430973973917901/) on January 16, 2012 08:04:36_

This is not a connector problem. https://code.google.com/p/syncope/issues/detail?id=271

**Status:** Invalid
