### ISSUE TITLE
Exception Handling - openAM connector

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldConnId#31]
_From [mdisabat...@gmail.com](https://code.google.com/u/101550733072735377085/) on February 07, 2012 14:20:20_

What steps will reproduce the problem? 1. Create new User with openam resource 

What is the expected output? 
User is successfully created.

What do you see instead?
User created but in the log:

3:51:36.743 DEBUG org.identityconnectors.framework.api.operations.GetApiOp.getObject Enter: getObject(ObjectClass: __ACCOUNT__, Attribute: {Name=__UID__, Value=[marco1]}, null)
13:51:36.778 DEBUG org.connid.openam.methods.OpenAMSearch.doExecuteQuery Search committed
13:51:36.778 ERROR org.connid.openam.methods.OpenAMSearch.doExecuteQuery User marco1 not exists
13:51:36.786 ERROR org.connid.openam.methods.OpenAMSearch.executeQuery error during execute query operation
java.lang.IllegalArgumentException: User marco1 not exists
	at org.connid.openam.methods.OpenAMExecuteQuery.doExecuteQuery(OpenAMExecuteQuery.java:60) ~[org.connid.bundles.openam-0.2-20120131.171147-1.jar:na]
	at org.connid.openam.methods.OpenAMExecuteQuery.executeQuery(OpenAMExecuteQuery.java:41) ~[org.connid.bundles.openam-0.2-20120131.171147-1.jar:na]
	at org.connid.openam.OpenAMConnector.executeQuery(OpenAMConnector.java:119) [org.connid.bundles.openam-0.2-20120131.171147-1.jar:na]
	at org.connid.openam.OpenAMConnector.executeQuery(OpenAMConnector.java:53) [org.connid.bundles.openam-0.2-20120131.171147-1.jar:na]
	at org.identityconnectors.framework.impl.api.local.operations.SearchImpl.rawSearch(SearchImpl.java:118) [framework-internal-1.3.1.jar:na]
	at org.identityconnectors.framework.impl.api.local.operations.SearchImpl.search(SearchImpl.java:82) [framework-internal-1.3.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_26]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_26]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_26]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_26]
	at org.identityconnectors.framework.impl.api.local.operations.ConnectorAPIOperationRunnerProxy.invoke(ConnectorAPIOperationRunnerProxy.java:93) [framework-internal-1.3.1.jar:na]
	at $Proxy186.search(Unknown Source) [na:na]
	at org.identityconnectors.framework.impl.api.local.operations.GetImpl.getObject(GetImpl.java:65) [framework-internal-1.3.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_26]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_26]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_26]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_26]
	at org.identityconnectors.framework.impl.api.local.operations.ThreadClassLoaderManagerProxy.invoke(ThreadClassLoaderManagerProxy.java:107) [framework-internal-1.3.1.jar:na]
	at $Proxy187.getObject(Unknown Source) [na:na]

_Original issue: http://code.google.com/p/connid/issues/detail?id=31_

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on February 07, 2012 05:23:30_

**Owner:** Massimil...@gmail.com  
  **Labels:** -Priority-Medium Priority-High Bundle-OpenAM

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on February 07, 2012 05:23:49_

**Blocking:** 26

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on February 07, 2012 05:45:08_

I'd suggest to check how other bundles behave in such cases: take LDAP or DBTable as reference.

**Comment by ilgrosso** [comment]
_From [Massimil...@gmail.com](https://code.google.com/u/103012165050613820067/) on February 08, 2012 02:34:45_

This issue was closed by revision r269 .

**Status:** Fixed
