### ISSUE TITLE
validate() reports exception about attempting to re-create existing view

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldConnId#54]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 07, 2012 14:13:56_

This was originally reported with Apache Syncope test configuration. 

Full stacktrace below.

18:43:19.078 ERROR org.connid.bundles.csvdir.database.FileToDB.bindFileTables While creating view USER_EX68673
java.sql.SQLSyntaxErrorException: object name already exists: USER_EX68673 in statement [CREATE VIEW USER_EX68673 AS SELECT * FROM CSV_TABLE56271]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb-2.2.8.jar:2.2.8]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb-2.2.8.jar:2.2.8]
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source) ~[hsqldb-2.2.8.jar:2.2.8]
	at org.hsqldb.jdbc.JDBCStatement.execute(Unknown Source) ~[hsqldb-2.2.8.jar:2.2.8]
	at org.connid.bundles.csvdir.database.FileToDB.bindFileTables(FileToDB.java:119) [org.connid.bundles.csvdir-0.5.jar:na]
	at org.connid.bundles.csvdir.database.FileToDB.createDbForSync(FileToDB.java:69) [org.connid.bundles.csvdir-0.5.jar:na]
	at org.connid.bundles.csvdir.CSVDirConnection.allCsvFiles(CSVDirConnection.java:205) [org.connid.bundles.csvdir-0.5.jar:na]
	at org.connid.bundles.csvdir.methods.CSVDirTest.execute(CSVDirTest.java:54) [org.connid.bundles.csvdir-0.5.jar:na]
	at org.connid.bundles.csvdir.methods.CSVDirTest.test(CSVDirTest.java:46) [org.connid.bundles.csvdir-0.5.jar:na]
	at org.connid.bundles.csvdir.CSVDirConnector.test(CSVDirConnector.java:274) [org.connid.bundles.csvdir-0.5.jar:na]
	at org.identityconnectors.framework.impl.api.local.operations.TestImpl.test(TestImpl.java:47) [framework-internal-1.3.2.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_37]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_37]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_37]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_37]
	at org.identityconnectors.framework.impl.api.local.operations.ConnectorAPIOperationRunnerProxy.invoke(ConnectorAPIOperationRunnerProxy.java:93) [framework-internal-1.3.2.jar:na]
	at $Proxy144.test(Unknown Source) [na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_37]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_37]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_37]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_37]
	at org.identityconnectors.framework.impl.api.local.operations.ThreadClassLoaderManagerProxy.invoke(ThreadClassLoaderManagerProxy.java:107) [framework-internal-1.3.2.jar:na]
	at $Proxy144.test(Unknown Source) [na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_37]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_37]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_37]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_37]
	at org.identityconnectors.framework.impl.api.DelegatingTimeoutProxy.invoke(DelegatingTimeoutProxy.java:107) [framework-internal-1.3.2.jar:na]
	at $Proxy144.test(Unknown Source) [na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_37]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_37]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_37]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_37]
	at org.identityconnectors.framework.impl.api.LoggingProxy.invoke(LoggingProxy.java:76) [framework-internal-1.3.2.jar:na]
	at $Proxy144.test(Unknown Source) [na:na]
	at org.identityconnectors.framework.impl.api.AbstractConnectorFacade.test(AbstractConnectorFacade.java:235) [framework-internal-1.3.2.jar:na]
	at org.apache.syncope.core.propagation.ConnectorFacadeProxy.test(ConnectorFacadeProxy.java:477) [ConnectorFacadeProxy.class:na]
	at org.apache.syncope.core.rest.controller.ConnInstanceController.check(ConnInstanceController.java:377) [ConnInstanceController.class:na]
	at org.apache.syncope.core.rest.controller.ConnInstanceController$$FastClassByCGLIB$$7de89b09.invoke(<generated>) [cglib-2.2.2.jar:na]
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [cglib-2.2.2.jar:na]
	at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689) [spring-aop-3.1.3.RELEASE.jar:3.1.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.1.3.RELEASE.jar:3.1.3.RELEASE]
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64) [spring-security-core-3.1.3.RELEASE.jar:3.1.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.1.3.RELEASE.jar:3.1.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110) [spring-tx-3.1.3.RELEASE.jar:3.1.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.1.3.RELEASE.jar:3.1.3.RELEASE]
	at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622) [spring-aop-3.1.3.RELEASE.jar:3.1.3.RELEASE]
	at org.apache.syncope.core.rest.controller.ConnInstanceController$$EnhancerByCGLIB$$4fcb4918.check(<generated>) [cglib-2.2.2.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_37]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_37]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_37]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_37]
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176) [spring-web-3.1.3.RELEASE.jar:3.1.3.RELEASE]
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:436) [spring-webmvc-3.1.3.RELEASE.jar:3.1.3.RELEASE]
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:424) [spring-webmvc-3.1.3.RELEASE.jar:3.1.3.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923) [spring-webmvc-3.1.3.RELEASE.jar:3.1.3.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852) [spring-webmvc-3.1.3.RELEASE.jar:3.1.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882) [spring-webmvc-3.1.3.RELEASE.jar:3.1.3.RELEASE]
	at org.springframewo...

_Original issue: http://code.google.com/p/connid/issues/detail?id=54_

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on January 07, 2013 04:53:50_

https://connid.atlassian.net/browse/CSVDIR-1

**Status:** Duplicate
